version: "3"
volumes :
  shared-workspace :
    name : "hadoop-distributed-file-system"
    driver : local
services:
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_WORKER_CORES=2"
      # - "SPARK_WORKER_MEMORY=512m"
      - "SPARK_MASTER=spark://spark-master:7077"
      - TZ=Asia/Seoul
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - "SPARK_WORKER_CORES=2"
      # - "SPARK_WORKER_MEMORY=512m"
      - "SPARK_MASTER=spark://spark-master:7077"
      - TZ=Asia/Seoul
    volumes:
      - shared-workspace:/opt/workspace
  py-spark:
    build: .
    depends_on:
      - spark-master
    environment:
      TZ: "Asia/Seoul"
    command : python3 -u example.py
    volumes:
      - ~/Spark-server:/opt
      - shared-workspace:/opt/workspace